name: Build Minecraft Mod

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Настройка Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Сборка мода (Build)
        run: gradle build

      - name: Сохранение .jar файла (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: AdvancedPvPMod-1.21.4
          path: build/libs/*.jar
